// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Api.Data.Snippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snippets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 3,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 4,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 5,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 6,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 7,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 8,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 9,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 10,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 11,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 12,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 13,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 14,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 15,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 16,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 17,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 18,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 19,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 20,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 21,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 22,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 23,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 24,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 25,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 26,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 27,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 28,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 29,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            Id = 30,
                            Description = "I just can't do it. You could see there was text coming out of her eyes, text coming out of her wherever. You have so many different things placeholder text has to be able to do, and I don't believe Lorem Ipsum has the stamina.",
                            FileUrl = "",
                            Title = "Lorem Ipsum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
